"""initial_schema

Revision ID: f1f04788fce5
Revises:
Create Date: 2026-08-10 16:41:44.219271

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1f04788fce5"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table(
        "categories",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("accent", sa.String(length=24), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("categories_pkey")),
    )
    op.create_index(op.f("categories_slug_idx"), "categories", ["slug"], unique=True)
    op.create_table(
        "orders",
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("customer_name", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=24), nullable=False),
        sa.Column("company_name", sa.String(length=180), nullable=True),
        sa.Column("edrpou", sa.String(length=10), nullable=True),
        sa.Column(
            "delivery_method",
            sa.Enum(
                "NOVA_POSHTA_BRANCH",
                "NOVA_POSHTA_LOCKER",
                "PICKUP",
                name="deliverymethod",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("delivery_city", sa.String(length=120), nullable=True),
        sa.Column("delivery_point", sa.String(length=200), nullable=True),
        sa.Column(
            "payment_method",
            sa.Enum(
                "CARD",
                "CASH_ON_DELIVERY",
                "INVOICE",
                name="paymentmethod",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "payment_status",
            sa.Enum(
                "PENDING",
                "NOT_REQUIRED",
                "PAID",
                "FAILED",
                "REFUNDED",
                name="paymentstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "PROCESSING",
                "CONFIRMED",
                "SHIPPED",
                "DELIVERED",
                "CANCELLED",
                name="orderstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("promo_code", sa.String(length=64), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("discount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("customer_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "discount >= 0", name=op.f("orders_order_discount_non_negative_check")
        ),
        sa.CheckConstraint(
            "subtotal >= 0", name=op.f("orders_order_subtotal_non_negative_check")
        ),
        sa.CheckConstraint(
            "total >= 0", name=op.f("orders_order_total_non_negative_check")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("orders_pkey")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("orders_idempotency_key_ukey")
        ),
    )
    op.create_index(op.f("orders_number_idx"), "orders", ["number"], unique=True)
    op.create_index(
        op.f("orders_payment_status_idx"), "orders", ["payment_status"], unique=False
    )
    op.create_index(op.f("orders_phone_idx"), "orders", ["phone"], unique=False)
    op.create_index(op.f("orders_status_idx"), "orders", ["status"], unique=False)
    op.create_table(
        "outbox_events",
        sa.Column("topic", sa.String(length=80), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "PROCESSED",
                "FAILED",
                name="outboxstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("outbox_events_pkey")),
    )
    op.create_index(
        op.f("outbox_events_locked_until_idx"),
        "outbox_events",
        ["locked_until"],
        unique=False,
    )
    op.create_index(
        op.f("outbox_events_next_attempt_at_idx"),
        "outbox_events",
        ["next_attempt_at"],
        unique=False,
    )
    op.create_index(
        op.f("outbox_events_status_idx"), "outbox_events", ["status"], unique=False
    )
    op.create_index(
        op.f("outbox_events_topic_idx"), "outbox_events", ["topic"], unique=False
    )
    op.create_table(
        "promotions",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("discount_rate", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "discount_rate > 0 AND discount_rate <= 1",
            name=op.f("promotions_promotion_discount_rate_range_check"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("promotions_pkey")),
    )
    op.create_index(op.f("promotions_code_idx"), "promotions", ["code"], unique=True)
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(op.f("users_username_idx"), "users", ["username"], unique=True)
    op.create_table(
        "subcategories",
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=96), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("subcategories_category_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("subcategories_pkey")),
        sa.UniqueConstraint(
            "category_id", "slug", name="subcategory_category_slug_ukey"
        ),
    )
    op.create_index(
        op.f("subcategories_category_id_idx"),
        "subcategories",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("subcategories_slug_idx"), "subcategories", ["slug"], unique=False
    )
    op.create_table(
        "products",
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("subcategory_id", sa.UUID(), nullable=True),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("brand", sa.String(length=120), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("old_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "badge",
            sa.Enum(
                "TOP", "SALE", "NEW", name="productbadge", native_enum=False, length=16
            ),
            nullable=True,
        ),
        sa.Column(
            "stock_status",
            sa.Enum(
                "IN_STOCK", "PREORDER", name="stockstatus", native_enum=False, length=24
            ),
            nullable=False,
        ),
        sa.Column("rating", sa.Numeric(precision=2, scale=1), nullable=False),
        sa.Column("reviews_count", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "old_price IS NULL OR old_price >= price",
            name=op.f("products_product_old_price_valid_check"),
        ),
        sa.CheckConstraint(
            "price >= 0", name=op.f("products_product_price_non_negative_check")
        ),
        sa.CheckConstraint(
            "rating >= 0 AND rating <= 5",
            name=op.f("products_product_rating_range_check"),
        ),
        sa.CheckConstraint(
            "reviews_count >= 0",
            name=op.f("products_product_reviews_count_non_negative_check"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("products_category_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subcategory_id"],
            ["subcategories.id"],
            name=op.f("products_subcategory_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("products_pkey")),
    )
    op.create_index(op.f("products_brand_idx"), "products", ["brand"], unique=False)
    op.create_index(
        op.f("products_category_id_idx"), "products", ["category_id"], unique=False
    )
    op.create_index(
        op.f("products_is_active_idx"), "products", ["is_active"], unique=False
    )
    op.create_index(op.f("products_name_idx"), "products", ["name"], unique=False)
    op.create_index(
        "products_name_trgm_idx",
        "products",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(op.f("products_sku_idx"), "products", ["sku"], unique=True)
    op.create_index(op.f("products_slug_idx"), "products", ["slug"], unique=True)
    op.create_index(
        op.f("products_stock_status_idx"), "products", ["stock_status"], unique=False
    )
    op.create_index(
        op.f("products_subcategory_id_idx"),
        "products",
        ["subcategory_id"],
        unique=False,
    )
    op.create_table(
        "leads",
        sa.Column(
            "type",
            sa.Enum(
                "CALLBACK",
                "QUICK_BUY",
                "WHOLESALE",
                name="leadtype",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "CONTACTED",
                "CLOSED",
                name="leadstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=24), nullable=False),
        sa.Column("company", sa.String(length=180), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("leads_product_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("leads_pkey")),
    )
    op.create_index(op.f("leads_phone_idx"), "leads", ["phone"], unique=False)
    op.create_index(op.f("leads_product_id_idx"), "leads", ["product_id"], unique=False)
    op.create_index(op.f("leads_status_idx"), "leads", ["status"], unique=False)
    op.create_index(op.f("leads_type_idx"), "leads", ["type"], unique=False)
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("product_name", sa.String(length=240), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("order_items_order_item_quantity_positive_check")
        ),
        sa.CheckConstraint(
            "total >= 0", name=op.f("order_items_order_item_total_non_negative_check")
        ),
        sa.CheckConstraint(
            "unit_price >= 0",
            name=op.f("order_items_order_item_price_non_negative_check"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("order_items_order_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("order_items_product_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("order_items_pkey")),
    )
    op.create_index(
        op.f("order_items_order_id_idx"), "order_items", ["order_id"], unique=False
    )
    op.create_index(
        op.f("order_items_product_id_idx"), "order_items", ["product_id"], unique=False
    )
    op.create_table(
        "product_attributes",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value", sa.String(length=160), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("product_attributes_product_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("product_attributes_pkey")),
        sa.UniqueConstraint(
            "product_id", "key", name="product_attribute_product_key_ukey"
        ),
    )
    op.create_index(
        op.f("product_attributes_key_idx"), "product_attributes", ["key"], unique=False
    )
    op.create_index(
        "product_attributes_key_value_idx",
        "product_attributes",
        ["key", "value"],
        unique=False,
    )
    op.create_index(
        op.f("product_attributes_product_id_idx"),
        "product_attributes",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("product_attributes_value_idx"),
        "product_attributes",
        ["value"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("product_attributes_value_idx"), table_name="product_attributes")
    op.drop_index("product_attributes_key_value_idx", table_name="product_attributes")
    op.drop_index(
        op.f("product_attributes_product_id_idx"), table_name="product_attributes"
    )
    op.drop_index(op.f("product_attributes_key_idx"), table_name="product_attributes")
    op.drop_table("product_attributes")
    op.drop_index(op.f("order_items_product_id_idx"), table_name="order_items")
    op.drop_index(op.f("order_items_order_id_idx"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("leads_type_idx"), table_name="leads")
    op.drop_index(op.f("leads_status_idx"), table_name="leads")
    op.drop_index(op.f("leads_product_id_idx"), table_name="leads")
    op.drop_index(op.f("leads_phone_idx"), table_name="leads")
    op.drop_table("leads")
    op.drop_index(op.f("products_subcategory_id_idx"), table_name="products")
    op.drop_index(op.f("products_stock_status_idx"), table_name="products")
    op.drop_index(op.f("products_slug_idx"), table_name="products")
    op.drop_index(op.f("products_sku_idx"), table_name="products")
    op.drop_index(op.f("products_name_idx"), table_name="products")
    op.drop_index("products_name_trgm_idx", table_name="products")
    op.drop_index(op.f("products_is_active_idx"), table_name="products")
    op.drop_index(op.f("products_category_id_idx"), table_name="products")
    op.drop_index(op.f("products_brand_idx"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("subcategories_slug_idx"), table_name="subcategories")
    op.drop_index(op.f("subcategories_category_id_idx"), table_name="subcategories")
    op.drop_table("subcategories")
    op.drop_index(op.f("users_username_idx"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("promotions_code_idx"), table_name="promotions")
    op.drop_table("promotions")
    op.drop_index(op.f("outbox_events_topic_idx"), table_name="outbox_events")
    op.drop_index(op.f("outbox_events_status_idx"), table_name="outbox_events")
    op.drop_index(op.f("outbox_events_next_attempt_at_idx"), table_name="outbox_events")
    op.drop_index(op.f("outbox_events_locked_until_idx"), table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index(op.f("orders_status_idx"), table_name="orders")
    op.drop_index(op.f("orders_phone_idx"), table_name="orders")
    op.drop_index(op.f("orders_payment_status_idx"), table_name="orders")
    op.drop_index(op.f("orders_number_idx"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("categories_slug_idx"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
